### ISSUE TITLE
August 2024 FDMS eBlast

### ISSUE THREAD

**Issue by cassandrajHall** [GSA-TTS/OROS-eRulemaking#101]
Word (docx) document for August 2024 FDMS submited from Agile5 Training to PMO Mon 7/15/2024. 
```[tasklist]
### Tasks
- [x] Convert docx to HTML via govDelivery
- [x] get FDMS user's list from Agile5 Helpdesk
- [x] Convert FDMS user's list to csv file
- [x] Upload FDMS user's list (csv) to govDelivery before distributing eBlast.
```

**Comment by cassandrajHall** [comment]
Task list created

**Comment by cassandrajHall** [comment]
eBlast completed. Sending to Agile5 Training team for review before distributing.

**Comment by cassandrajHall** [comment]
Worked with Agile5 Training leads to correct training registration links. eBlasts distributed to FDMS users.
