### ISSUE TITLE
Draft modernization KPIs FY25

### ISSUE THREAD

**Issue by atabing11** [GSA-TTS/OROS-eRulemaking#106]
```[tasklist]
### Tasks
- [x] Refine performance metrics/goals in this doc: https://docs.google.com/document/d/1LfvFuVUA147fXQH8lWLhTiSX-Y62T-mIvRgp23YNAfg/edit?tab=t.0
- [ ] Share out performance metrics with eR team
- [ ] Share out performance metrics with larger dev/platform team
```

**Comment by atabing11** [comment]
https://docs.google.com/document/d/1LfvFuVUA147fXQH8lWLhTiSX-Y62T-mIvRgp23YNAfg/edit?tab=t.0
