### ISSUE TITLE
Compile and investigate FDMS metadata -> subtypes

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#129]
Team to investigate and compile a list of FDMS metadata, particularly docket and document subtypes, with the goal to crosswalk and/or narrow down to fewer subtypes in the modern platform.

```[tasklist]
### Tasks
- [x] Engage engineering to compile an in-app current subtype list
- [ ] Compile into linked google sheet
- [ ] Research with agencies to crosswalk into most effective categories, collab with Heidi on this
- [ ] Finalize metadata subtypes and document finalization
```

[FDMS v5 Metadata Google Sheet](https://docs.google.com/spreadsheets/d/15fE5ObUTwtxkf9BB-JwYPZUoJW1iZWCCowlvV8rNjyI/edit?gid=0#gid=0)
