### ISSUE TITLE
HHS Designation Update (Carrie Shelton Replacement) for eR Boards & Google Groups

### ISSUE THREAD

**Issue by cassandrajHall** [GSA-TTS/OROS-eRulemaking#136]
From: Carrie.Shelton@hhs.gov

Hi Cassandra,
I’m departing HHS at the end of the week, and so I should be removed from the HHS roster for the various eRulemaking workgroups.  Wilma will remain HHS’s representative for the Executive Steering Committee, and Sam will replace me on the AB and CCB (and Calvin will continue to sit on the CCB, as well).
Thanks!
Carrie
 
 
Carrie Shelton | IOS/Exec Sec | 202-690-6827 | [Carrie.Shelton@hhs.gov](mailto:Carrie.Shelton@hhs.gov) |

```[tasklist]
### Tasks
- [x] Update eRulemaking ESC, AB, CCB and BWG Governance Rosters spreadsheet
- [ ] Update MR ESC Google Group
- [ ] Update MR CCB Google Group
- [ ] Update MR AB Google Group
- [ ] Update MR Budget Working Group
```

**Comment by cassandrajHall** [comment]
Google Groups updated (Remove Carrie.Shelton@hhs.gov; Add Samuel.Shipley@hhs.gov)
AB: https://groups.google.com/a/gsa.gov/g/AdvisoryBoard_ER_PMO (Sam already a member. Removed Carrie)
CCB: https://groups.google.com/a/gsa.gov/g/RegulationManagementCCB (Added Sam; Carrie not a member)
ESC: https://groups.google.com/a/gsa.gov/g/ESC_ER_PMO (Sam already a member. Removed Carrie)
BWG: https://groups.google.com/a/gsa.gov/g/Budget_ER_PMO (Removed Carrie. Added Sam)
