### ISSUE TITLE
FDMS search and filter updates

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#14]
```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/OROS-eRulemaking/issues/15
- [ ] https://github.com/GSA-TTS/OROS-eRulemaking/issues/49
- [ ] https://github.com/GSA-TTS/OROS-eRulemaking/issues/51
```

**Comment by ianhabit-gsa** [comment]
Tracking for release mid June.

**Comment by ianhabit-gsa** [comment]
Revised LoE for delivery is now July since we have sliced the team's to focus on modernization. This includes testing, development, UAT and post UAT changes, and release. @atabing11
