### ISSUE TITLE
Investigate records management and determine recommendation on modernization

### ISSUE THREAD

**Issue by atabing11** [GSA-TTS/OROS-eRulemaking#156]
https://cm-jira.usa.gov/browse/ERULE-10113

```[tasklist]
### Tasks
- [ ] Document current records management requirements (policies)
- [ ] Document previous records management capability and module
- [ ] Discuss with engineering any architectural implications of records management
- [ ] Determine timeframe for making a decision (based on architectural impact or estimate of size)
- [ ] Interviews with records management agencies
- [ ] Interview FDA on records management process
```

**Comment by atabing11** [comment]
Important links:

- Records management in FDMS v4: https://drive.google.com/file/d/1Yi02YkLVbTqZ8SfDinZ9VhUl4LH8nGHz/view?usp=drive_link
- Records policy mandates: https://docs.google.com/document/d/1OWY-qqSFG0jagHT5xye2ovG9PBTVlnGAD9LlwNSJ32g/edit
- https://www.archives.gov/records-mgmt/policy/universalermrequirements
