### ISSUE TITLE
Comment analysis 0.2 scope

### ISSUE THREAD

**Issue by atabing11** [GSA-TTS/OROS-eRulemaking#162]
```[tasklist]
### Tasks
- [x] Draft objectives and success metrics
- [x] Draft high level user stories/needs
- [ ] Draft user flows
```

**Comment by atabing11** [comment]
https://docs.google.com/document/d/1S0yjj5C-eUPJhYyUK7MI7czOt-fB7dKOpeaHKiarosc/edit#heading=h.qosm13bofcdz
