### ISSUE TITLE
June E-Blast for FDMS

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#20]
```[tasklist]
### Tasks
- [x] Work with Heidi to review/approve eBlast content for June 2024
- [ ] Awaiting receipt of FDMS user list for June 2024 (Agile5 - Tyler Coleman)
- [ ] Convert *.docx to HTML format in govDelivery
```
