### ISSUE TITLE
FDMS User Account Audit

### ISSUE THREAD

**Issue by cassandrajHall** [GSA-TTS/OROS-eRulemaking#25]
```[tasklist]
### Tasks
- [x] Meet with Jake Brozenick for planning
- [x] Coordinate with Dyna Digby for Partner Agency comms
- [x] Coordinate with Agile5 Training/Helpdesk for lists
- [x] Coordinate with Agile5 Training for June AA Account Maintenance training
- [ ] Validate AAs designation with eR Board POCs where emails invalid (bounces or blocked)
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by ianhabit-gsa** [comment]
Jake Brozenick provided Heidi with the NIST information and best practice to remind agency admins how to manage user accounts in FDMS (quarterly cleaning of accounts).

**Comment by cassandrajHall** [comment]
Agile5 Refresher Training for Agency Admins completed May 29th.

**Comment by cassandrajHall** [comment]
May 29th eBlast gave Agency Admins June 5th deadline to update FDMS users.
Reminder email sent to Agency Admins on June 5th (several responses and requests for help to Heidi).
PMO sent email to Agency Board POCs for Agency Admins accounts not active (3-agencies). Forth agency/group (PCSCOTUS) not listed in Partner Agency spreadsheet.

**Comment by cassandrajHall** [comment]
Monitoring Agency account removals. EPA requested extension to June 5th deadline in lieu of massive no of accounts to review. Agile5 Training Lead emailed reminders to Agencies Friday 6/7/2024 with June 14th deadline. Tier 2 will remove remaining inactive accounts on June 17th.
