### ISSUE TITLE
Docket Services - OSHA short term

### ISSUE THREAD

**Issue by cassandrajHall** [GSA-TTS/OROS-eRulemaking#27]
```[tasklist]
### Tasks
- [x] FedWriters Mod to contract for new OSHA CLIN Pending
- [x] Access to SLA Google doc template for new June 2024 OSHA short term surge
- [ ] Coordinate with BizOps for IAA
```

```[tasklist]
### Tasks
```

**Comment by cassandrajHall** [comment]
Draft SLA Link: https://docs.google.com/document/d/1nTIBtVIekeS_bEFmnLyC34qsqiZ20eb1P7H-3Rfdrh4/edit?usp=sharing
Provided estimate volume of comments to FedWriters PM.
Received estimate processing time (hours) based upon volume of comments provided.
Calculated support dollars needed from OSHA to provide services. Appended cost figures to SLA.
Emailed (docx and pdf versions) to OSHA for review and staffing on Monday, 6/3/2024.

**Comment by cassandrajHall** [comment]
BizOps (Shelley Goss) submitted the GT&C in G-invoicing DoL (OSHA) to review/sign. The GT&C number is  A2407-016-047-064266. Awaiting return of draft SLA from OHSA's review to be returned today, Mon 7/8/2024 as confirmed from email from OSHA PM (Michelle Payton) today.

**Comment by cassandrajHall** [comment]
OSHA returned updated SLA and "clean" version of updated [SLA document](https://docs.google.com/document/d/17E0dIqdQs_nhNYVxj02LkrudeGc_tX7i/edit?usp=drive_link).  Provided link for Google Drive and document to BizOps (Shelley Goss) and OROS Finance/Budget Analyst (Kevin Funches).

**Comment by cassandrajHall** [comment]
July 24 - OSHA requested to meet for final performance standards. Zoom meeting scheduled for Monday, 7/29/2024 12:30pm

**Comment by cassandrajHall** [comment]
Facilitted meeting on 7/29/2024 between FedWriters and OSHA (Michelle Walker and Davina Brown) to cover performance metrics and processing. OSHA reported that IAA was signed and completed that morning. OSHA requested suport from FedWriter to begin as soon as access could be granted to FedWriters team. Support is underway.

**Comment by cassandrajHall** [comment]
OSHA reported sufficient progress in processing support documentation on their  Heat Injury and Illness Prevention in Outdoor and Indoor Work Settings (OSHA-2021-0009) NPRM to date. They requested to meet to provide criteria/comment processing protocols for the Emergency Response (ER) NPRM. Zoom meeting scheduled for Thursday, Aug 8th 2-2:45pm ET.

**Comment by cassandrajHall** [comment]
Meeting successful. Performance criteria provide for Emergency Response NPRM. A walkthrough of comments processing demonstrated within FDMS to Docket Service leads. Support from Docket Service team initiated immediately following the meeting. Questions from Docket Services to OSHA Docket Manager (Davina) were emailed, as OSHA DM is OOO all next week.

**Comment by cassandrajHall** [comment]
Support completed Aug 23, 2024.
