### ISSUE TITLE
Content model for docket, document, and comments

### ISSUE THREAD

**Issue by atabing11** [GSA-TTS/OROS-eRulemaking#3]
```[tasklist]
### Tasks
- [ ] Initial content model for dockets
- [ ] Initial content model for documents
- [ ] Initial content model for comments
- [ ] High level functional and technical requirements documented 
```
