### ISSUE TITLE
TO6 tech eval and continued pre-award

### ISSUE THREAD

**Issue by atabing11** [GSA-TTS/OROS-eRulemaking#33]
https://drive.google.com/drive/u/0/folders/1sfIVXon6thY4X3-231nHn6C0TlIHazBu

```[tasklist]
### Tasks
- [ ] Follow up on any AAS questions
- [ ] Select technical evaluation board members
- [ ] Coordinate with Shelley to provide funding when required
```
