### ISSUE TITLE
USWDS component audit

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#39]
```[tasklist]
### Tasks
- [ ] Confirm lo-fi wireframes are heading in the right direction
- [ ] Conduct audit of USWDS component library to see what we can use or build off of.
- [ ] Examine areas of USWDS that are missing that we need to build from scratch
- [ ] Confirm BeInformed can accomodate a custom UI
```

**Comment by ianhabit-gsa** [comment]
Deprecated as of 6/10/24
