### ISSUE TITLE
Modernization wireframe design

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#4]
```[tasklist]
### Tasks
- [x] Complete lo-fi wireframes for public views/workflows
- [x] Mid-fi wireframes of public view/workflows to inform agency workflows
- [x] Lo-fi wireframes for agency views/workflows
- [x] Assess mid-fi agency design for document details page and comments page - provide feedback to Sammy
```

**Comment by ianhabit-gsa** [comment]
Lo-fi's for public view reviewed and approved by Alex and Ian. 

Ian to instruct Sammy to start on making those mid-fi's with some options going forward.
