### ISSUE TITLE
Schedule Budget Working Group session

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#40]
```[tasklist]
### Tasks
- [x] Update BWG Google Group
- [x] Validate POCs with Agency Leads
- [x] Schedule WG sessions
```

**Comment by cassandrajHall** [comment]
Placeholder (tentative schedules) set as requested: "set up placeholder invitations for the respective Governance groups from slide 9, all for 1hr each, starting at 9:30am.  For the the AB/CCB on June 26, you can also include BW.  Similarly for the July 11 ESC, you can include BW, AB, CCB."

**Comment by cassandrajHall** [comment]
Modified meeting schedule (as requested). Updated Zoom meeting links for all dates.
