### ISSUE TITLE
Establish FDMS working group

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#43]
```[tasklist]
### Tasks
- [x] Look at Qualtrics data to determine group composition
- [x] Send out note to group to find a time in June
- [ ] Schedule June meeting based on responses
- [ ] Create team charter from 18F template
- [ ] Create June meeting agenda
```
