### ISSUE TITLE
FY26 Budget Activities

### ISSUE THREAD

**Issue by ianhabit-gsa** [GSA-TTS/OROS-eRulemaking#5]
```[tasklist]
### Tasks
- [ ] Determine final FY24 revenues
- [ ] Determine and log other salary agreements
- [ ] Finalize misc purchases list
- [ ] https://github.com/GSA-TTS/OROS-eRulemaking/issues/19
```
